### ISSUE TITLE
SDK Intermittently Becomes Unresponsive in Google App Engine

### ISSUE THREAD

**Issue by hiranya911** [firebase/firebase-admin-java#29]
* Environment: Google App Engine (Java runtime)

Admin Java SDK sometimes becomes unresponsive after operating without problems for several days. Issue is random and intermittent. There are no specific error messages or stack traces dumped when this happens.

After analyzing the App Engine logs for a user application that encounters this issue regularly, we have identified the following issue which is a strong candidate for the root cause (a 100% certain diagnosis is not possible due to the lack of error traces).

When the SDK encounters a connection issue (due to a backend server restart, or some other networking issue), which lasts longer than 2-3 seconds, the SDK starts running reconnect attempts aggressively. Each attempt instantiates 2 Threads (socket reader and writer). If the reader terminates with an error, which is the case with an extended connectivity issue, the writer thread will never even start. However, such leaked threads count towards the thread quota (10) of Google App Engine. After a number of reconnect attempts the SDK will get into a state where it can no longer launch new threads, and therefore cannot re-establish the connection with Firebase.

Another related cause could be the rate at which the SDK runs reconnect attempts. This is supposed to be a variant of exponential backoff, but due to a high jitter (probabilistic) factor, SDK ends up running a large number of reconnect attempts in a short span of time. Thread creation and termination are expensive operations in GAE, and it might make sense to lower the jitter factor so that exponential backoff takes effect.

**Comment by erikmejias** [comment]
Any updates about this bug? I've been experiencing it.

**Comment by hiranya911** [comment]
You can try the fix made at #30 and see if that resolves your issue. If you can provide any code to reproduce the issue, or provide some debug logs that would be helpful to us.

**Comment by hiranya911** [comment]
This fix is available in the 5.0.1 release that went out today. I'll close this ticket as fixed. If we continue to see issues in App Engine even with the new version, we can revisit this.

**Comment by Nic0w** [comment]
This bug still exists and @hiranya911's description of the problem is pretty accurate. 

Everything works fine until requests making use of Firebase Realtime Database start to hang and return 502 errors (that don't show up in Google App Engine request logs...). After having to deal with these very strange errors quite a few time on different instances, we enabled the  DEBUG logging on FirebaseDatabase and here is what happens in the SDK when the 502 errors start to appear : 
[log_extract.txt](https://github.com/firebase/firebase-admin-java/files/1585771/log_extract.txt)

retries go on like for 6 hours until it miraculously reconnect, and then the two following stacktraces show up : 

> [e~project-dev-nic0w/deploy-4-232-g65f2a50-dirty.406449105320946253].<stderr>: Mon Dec 25 06:46:53 UTC 2017 [ERROR] com.google.firebase.database.core.RunLoop: Uncaught exception in Firebase Database runloop (5.6.0). Please report to firebase-database-client@google.com
java.lang.IllegalStateException: Limit on the number of active background requests was reached for this app version.
	at com.google.appengine.api.system.SystemServiceImpl.translateException(SystemServiceImpl.java:42)
	at com.google.appengine.api.system.SystemServiceImpl.startBackgroundRequest(SystemServiceImpl.java:28)
	at com.google.apphosting.runtime.ApiProxyImpl$BackgroundThreadFactory.newThread(ApiProxyImpl.java:1316)
	at com.google.firebase.internal.GaeThreadFactory.newThread(GaeThreadFactory.java:78)
	at com.google.firebase.internal.RevivingScheduledExecutor$1.newThread(RevivingScheduledExecutor.java:103)
	at java.util.concurrent.ThreadPoolExecutor$Worker.<init>(ThreadPoolExecutor.java:612)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:925)
	at java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1587)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:336)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:555)
	at java.util.concurrent.ScheduledThreadPoolExecutor.execute(ScheduledThreadPoolExecutor.java:644)
	at com.google.firebase.internal.RevivingScheduledExecutor.execute(RevivingScheduledExecutor.java:122)
	at com.google.firebase.database.core.ThreadPoolEventTarget.postEvent(ThreadPoolEventTarget.java:58)
	at com.google.firebase.database.core.view.EventRaiser.raiseEvents(EventRaiser.java:50)
	at com.google.firebase.database.core.Repo.postEvents(Repo.java:248)
	at com.google.firebase.database.core.Repo.onDataUpdate(Repo.java:307)
	at com.google.firebase.database.connection.PersistentConnectionImpl.onDataPush(PersistentConnectionImpl.java:668)
	at com.google.firebase.database.connection.PersistentConnectionImpl.onDataMessage(PersistentConnectionImpl.java:278)
	at com.google.firebase.database.connection.Connection.onDataMessage(Connection.java:166)
	at com.google.firebase.database.connection.Connection.onMessage(Connection.java:120)
	at com.google.firebase.database.connection.WebsocketConnection.appendFrame(WebsocketConnection.java:171)
	at com.google.firebase.database.connection.WebsocketConnection.handleIncomingFrame(WebsocketConnection.java:210)
	at com.google.firebase.database.connection.WebsocketConnection.access$800(WebsocketConnection.java:44)
	at com.google.firebase.database.connection.WebsocketConnection$WSClientHandlerImpl$2.run(WebsocketConnection.java:302)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:295)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.google.apphosting.runtime.ApiProxyImpl$BackgroundThreadFactory$1$1.run(ApiProxyImpl.java:1305)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.google.apphosting.runtime.ApiProxyImpl$BackgroundThreadFactory$1.run(ApiProxyImpl.java:1299)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchBackgroundRequest(JavaRuntime.java:664)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:639)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:612)
	at com.google.apphosting.runtime.JavaRuntime$NullSandboxRequestRunnable.run(JavaRuntime.java:806)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:274)
	at java.lang.Thread.run(Thread.java:745)

Which in turns lead the background thread to be killed : 

> Uncaught exception from servlet
java.lang.IllegalStateException: Limit on the number of active background requests was reached for this app version.
	at com.google.appengine.api.system.SystemServiceImpl.translateException(SystemServiceImpl.java:42)
	at com.google.appengine.api.system.SystemServiceImpl.startBackgroundRequest(SystemServiceImpl.java:28)
	at com.google.apphosting.runtime.ApiProxyImpl$BackgroundThreadFactory.newThread(ApiProxyImpl.java:1316)
	at com.google.firebase.internal.GaeThreadFactory.newThread(GaeThreadFactory.java:78)
	at com.google.firebase.internal.RevivingScheduledExecutor$1.newThread(RevivingScheduledExecutor.java:103)
	at java.util.concurrent.ThreadPoolExecutor$Worker.<init>(ThreadPoolExecutor.java:612)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:925)
	at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1018)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.google.apphosting.runtime.ApiProxyImpl$BackgroundThreadFactory$1$1.run(ApiProxyImpl.java:1305)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.google.apphosting.runtime.ApiProxyImpl$BackgroundThreadFactory$1.run(ApiProxyImpl.java:1299)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchBackgroundRequest(JavaRuntime.java:664)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.dispatchRequest(JavaRuntime.java:639)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:612)
	at com.google.apphosting.runtime.JavaRuntime$NullSandboxRequestRunnable.run(JavaRuntime.java:806)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:274)
	at java.lang.Thread.run(Thread.java:745)

**Comment by hiranya911** [comment]
Which version of the SDK are you using? This should not happen in recent versions, provided you're not accessing/instantiating more than one database instance. Can you describe how you initialize FirebaseApp and FirebaseDatabase in your app?

I'm also pretty sure there hasn't been any extended outages in the recent past (definitely not one that lasted 6 hours). If there were we would have received a lot more error reports.

**Comment by Nic0w** [comment]
Hi @hiranya911,
We're using Firebase Admin SDK 5.6.0.
Regarding FirebaseApp and FirebaseDatabase init, we have a custom ServletContextListener with the following code in the contextInitialized method : 
`    FirebaseApp defaultApp = null;
    
    try {
      
      defaultApp = FirebaseApp.getInstance(Constants.DEFAULT_FIREBASE_APP);
      
    } catch (IllegalStateException e) {
      
      LOGGER.log(Level.INFO, "Firebase was not initialized.", e);
      FirebaseOptions options = new FirebaseOptions.Builder()
              .setCredentials(GoogleCredentialFactory.Companion.getCredential())
              .setDatabaseUrl(Constants.FIREBASE_RTDB_URL)
              .build();

      defaultApp = FirebaseApp.initializeApp(options, Constants.DEFAULT_FIREBASE_APP);
    }
    
    FirebaseDatabase database = FirebaseDatabase.getInstance(defaultApp);
    torchDatabase.setLogLevel(com.google.firebase.database.Logger.Level.DEBUG);
    
    SomeInterfaceImpl firebaseStorage = new SomeInterfaceImpl(database.getReference());

    //singleton
    DataAccessFactory.buildStorageInstance(firebaseStorage);
    
    LOGGER.warning("Done initializing Firebase.");    `
Hi @hiranya911,
We're using Firebase Admin SDK 5.6.0.
Regarding FirebaseApp and FirebaseDatabase init, we have a custom ServletContextListener with the following code in the contextInitialized method : 
`    FirebaseApp defaultApp = null;
    
    try {
      
      defaultApp = FirebaseApp.getInstance(Constants.DEFAULT_FIREBASE_APP);
      
    } catch (IllegalStateException e) {
      
      LOGGER.log(Level.INFO, "Firebase was not initialized.", e);
      FirebaseOptions options = new FirebaseOptions.Builder()
              .setCredentials(GoogleCredentialFactory.Companion.getCredential())
              .setDatabaseUrl(Constants.FIREBASE_RTDB_URL)
              .build();

      defaultApp = FirebaseApp.initializeApp(options, Constants.DEFAULT_FIREBASE_APP);
    }
    
    FirebaseDatabase database = FirebaseDatabase.getInstance(defaultApp);
    torchDatabase.setLogLevel(com.google.firebase.database.Logger.Level.DEBUG);
    
    SomeInterfaceImpl firebaseStorage = new SomeInterfaceImpl(database.getReference());

    //singleton
    DataAccessFactory.buildStorageInstance(firebaseStorage);
    
    LOGGER.warning("Done initializing Firebase."); `

**Comment by hiranya911** [comment]
Thanks @Nic0w. The initialization code looks good. At this point I don't have a specific explanation as to what may have caused this. Possible reasons include:

1. A bug in the SDK: We did some changes in SDK's WebSocket layer in v5.5.0. It is possible something went wrong there.
2. A transient network error in App Engine
3. A transient error in Firebase RTDB, localized to your database instance

We need more details to debug/investigate this. GitHub is not really suitable for this, so I'd recommend you to report it via the official Firebase support channel: https://firebase.google.com/support/contact/bugs-features/

Please provide as much details as possible. Specifically:

* Your App Engine project ID and RTDB URL
* Frequency of errors: Did it happen only once, or do you encounter is regularly?
* Any and all debug logs you have collected (just zip them all up and upload)
* Is this a new app, or an old app upgraded to use the Admin SDK 5.6.0?
* Do you start any additional threads in your app, except for the ones started by the SDK?
* If you can share your full source code that would be great too.

Hopefully this will help us track down the exact root cause. Sorry for troubling you with all these requests, but if there is a bug we'd really like to get to the bottom of it, and fix asap. Thanks again for reporting this.

**Comment by Nic0w** [comment]
I reported the issue through the official Firebase channel as you asked, @hiranya911.
However I was not able to attach a zip with the full logs for this issue ("File type not allowed"), nor was I able to send the raw txt file (error 500 after submitting the form), maybe because the file is too big (5.9 MB of logs).

Anyway, I'm hoping this issue will be resolved shortly.
Thank you for your help :)

**Comment by hiranya911** [comment]
Thanks @Nic0w. Please hold on to the logs. Somebody will get in touch with you over the course of next week, and you will be able to share the files then.
